version: 2.1

# ===================
# Shared definitions.
# ===================
defaults: &defaults
  docker:
    - image: docker:18-git
  working_directory: ~/clickhouse-operator

# ====================
# WORKFLOW DECLARATION
# ====================
workflows:
  version: 2
  main:
    jobs:
      - build_and_deploy:
        branches:
          only:
            - master

# ================
# JOB DECLARATIONS
# ================
jobs:
  build_and_deploy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Docker Hub.
          command: |
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - run:
          name: Build Docker image.
          command: |
            echo 'export CHO_RELEASE=$(cat release)' >> $BASH_ENV
            docker build -t $CHO_NAME:latest .
      - run:
          name: Pushing Docker image
          command: |
            source $BASH_ENV
            if [ "$CIRCLE_BRANCH" = 'master' ]; then
              docker tag $CHO_NAME:latest $COMPANY_REPO/$CHO_NAME:latest
              docker tag $CHO_NAME:latest $COMPANY_REPO/$CHO_NAME:current
              docker tag $CHO_NAME:latest $COMPANY_REPO/$CHO_NAME:$CHO_RELEASE
              docker push $COMPANY_REPO/$CHO_NAME:latest
              docker push $COMPANY_REPO/$CHO_NAME:current
              docker push $COMPANY_REPO/$CHO_NAME:$CHO_RELEASE
            fi
